### ISSUE TITLE
datasets

### ISSUE THREAD

**Issue by yffbk** [mtailanian/diff-cf#1]
What exactly does the directory of the dataset folder look like? Looking forward to your reply, thank you.

**Comment by mtailanian** [comment]
Hello @yffbk.
A description is already included in the README file. Pasting screenshot here:
![image](https://github.com/user-attachments/assets/a1f93195-597f-427e-9888-3a9334bc49db)

Let me know if you have any specific questions, if that's not enough...

**Comment by 123gjj** [comment]
如果我想要添加其他噪声是不是需要重新训练呢？怎么训练呢？期待您的回复谢谢。

**Comment by mtailanian-digitalsense** [comment]
Hello, for this work, we use a pre-trained diffusion model, and therefore, we do not provide code for training, as we did not do it.

However, the code is based on [this repo](https://github.com/openai/guided-diffusion), which has instructions for training.

Hope it helps...

**Comment by mtailanian** [comment]
Hello, for this work, we use a pre-trained diffusion model, and therefore, we do not provide code for training, as we did not do it.

However, the code is based on [this repo](https://github.com/openai/guided-diffusion), which has instructions for training.

Hope it helps...

**Comment by 123gjj** [comment]
> 您好，对于这项工作，我们使用了预先训练的扩散模型，因此，我们不提供用于训练的代码，因为我们没有这样做。
> 
> 但是，该代码基于[此存储库](https://github.com/openai/guided-diffusion)，其中包含培训说明。
> 
> 希望它有帮助......
您好，那如果我想要修改代码结构，例如更改噪声类型等操作，还能继续使用预先训练的扩散模型吗？

**Comment by mtailanian** [comment]
Hello, you would need to retrain, as the denoised is specialized to the noise seen during training.
